import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Card from "../src/components/Card";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>List of Pages in this project</h1>
        <section className={styles.pages}>
          <Card
            title="Posts"
            content="Posts page having a bunch of posts posted by different users"
            link="/posts"
          />
        </section>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
